import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    getStarted: 'Get Started',
    analyzeMyCV: 'Analyze My CV',
    forCandidates: 'For Candidates',
    forRecruiters: 'For Recruiters',
    signIn: 'Sign In',
    home: 'Home',
    dashboard: 'Dashboard',
    myCVs: 'My CVs',
    settings: 'Settings',
    signOut: 'Sign Out',
    chooseYourRole: 'Choose Your Role',
    selectHowYouUseHirevion: 'Select how you want to use Hirevion',
    imHiring: "I'm hiring and want to find candidates",
    iWantToAnalyze: "I want to analyze and improve my CV",
    // Landing pages
    chooseYourPath: 'Choose Your Path',
    selectHowUseHirevion: 'Select how you want to use Hirevion',
    exploreHiring: 'Explore Hiring',
    analyzeMyCV: 'Analyze My CV',
    jeSuisRecruteur: 'Je suis Recruteur',
    jeSuisTalent: 'Je suis Talent',
    findCandidates: 'Find Perfect Candidates',
    findCandidatesDesc: 'Discover exceptional talent through our advanced AI matching system. Upload CVs, define requirements, get ranked candidates instantly.',
    findCandidatesTitle: 'Find the Perfect Candidates with AI',
    improveCV: 'Analyze & Improve Your CV',
    improveCVDesc: 'Upload your CV and get instant feedback. Discover your strengths, weak points, and personalized suggestions to stand out.',
    improveCVTitle: 'Analyze & Improve your CV with AI',
    getStartedFree: 'Get Started Free',
    viewDemo: 'View Demo',
    scheduleDemo: 'Schedule Demo',
    whyRecruitersChoose: 'Why Recruiters Choose Hirevion?',
    powerfulAI: 'Powerful AI tools to transform your hiring process',
    bulkProcessing: 'Bulk Processing',
    bulkProcessingDesc: 'Upload dozens of CVs at once. AI ranks all candidates instantly with clear recommendations.',
    startFreeToday: 'Start Free Today',
    join500Recruiters: 'Join 500+ Recruiters',
    readyToTransform: 'Ready to Transform Your Hiring?',
    hiringDesc: 'Start finding exceptional candidates today. No credit card required.',
    threeSimpleSteps: 'Three simple steps to find your ideal candidates',
    whyTalentsLove: 'Why Talents Love Hirevion?',
    improveChances: 'Get professional feedback and improve your chances',
    instantAnalysis: 'Instant Analysis',
    instantAnalysisDesc: 'Upload your CV and get detailed feedback within seconds. Know your score immediately.',
    improvementTips: 'Improvement Tips',
    improvementTipsDesc: 'Get specific suggestions to boost your CV. Actionable tips from AI experts.',
    atsOptimization: 'ATS Optimization',
    atsOptimizationDesc: 'Ensure your CV passes Applicant Tracking Systems. Get noticed by recruiters.',
    threeSimpleStepsCV: 'Simple three steps to improve your CV',
    standOut: 'Ready to Stand Out?',
    standOutDesc: 'Analyze your CV now and get discovered by top companies.',
    join1000Talents: 'Join 1000+ Talents',
    seeDemoResults: 'See Demo Results',
    matchRate: 'Match Rate',
    skillsDetected: 'Skills Detected',
    cvsAnalyzed: 'CVs Analyzed',
    goodMatch: 'Good',
    strongMatch: 'Strong',
    needsWork: 'Needs Work',
    aiSuggestions: 'AI Suggestions',
    atsFriendly: 'ATS Friendly',
    ninetyFiveBetter: '95% Better',
    findPerfectProfile: 'Find the Perfect Profile with AI',
    hirevionDescription: 'Hirevion connects exceptional profiles with forward-thinking companies. Our AI analyzes skills, experience, and potential to find your perfect match.',
    matchAccuracy: 'Match Accuracy',
    fasterHiring: 'Faster Hiring',
    companiesTrustUs: 'Companies Trust Us',
    whyChooseHirevion: 'Why Choose Hirevion?',
    revolutionaryAI: 'Revolutionary AI technology for modern recruitment',
    aiPoweredMatching: 'AI-Powered Matching',
    aiMatchingDesc: 'Advanced algorithms analyze skills, experience, and potential. Smart skill similarity detection recognizes related technologies.',
    detailedAnalytics: 'Detailed Analytics',
    analyticsDesc: 'Get comprehensive scoring breakdowns: skills (40%), experience (25%), education (15%), domain fit (20%).',
    flexibleSelection: 'Flexible Selection',
    selectionDesc: '4-tier system: Excellent (80-100%), Good (65-79%), Potential (50-64%). Find candidates with potential, not just perfect matches.',
    howItWorks: 'How Hirevion Works',
    simpleProcess: 'Simple 3-step process to find your ideal candidates',
    uploadCVs: 'Upload CVs',
    uploadCVsDesc: 'Upload multiple PDF CVs. Our AI extracts structured data including skills, experience, education, and projects.',
    defineJob: 'Define Job',
    defineJobDesc: 'Enter job title, number of positions, and requirements. AI structures the profile and identifies key skills needed.',
    getResults: 'Get Results',
    getResultsDesc: 'Receive ranked candidates with detailed scoring, skill analysis, strengths/weaknesses, and hiring recommendations.',
    readyToTransform: 'Ready to Transform Your Hiring?',
    joinCompanies: 'Join hundreds of companies who have streamlined their hiring process with Hirevion\'s AI-powered platform.',
    startFreeToday: 'Start Free Today',
    uploadYourCV: 'Upload Your CV',
    join500Companies: 'Join 500+ Companies',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    forgotPassword: 'Forgot Password?',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordDesc: 'Enter your email and we\'ll send you a reset link',
    resetPassword: 'Reset Password',
    backToLogin: 'Back to Login',
    // FAQ Section
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Everything you need to know about Hirevion',
    faqQuestion1: 'How does Hirevion\'s AI matching work?',
    faqAnswer1: 'Our AI analyzes CVs and job requirements using advanced natural language processing. It extracts skills, experience, education, and more to calculate compatibility scores across multiple dimensions.',
    faqQuestion2: 'Is my data secure?',
    faqAnswer2: 'Absolutely. We use enterprise-grade encryption and never share your data with third parties. Your CVs and company information are kept completely confidential.',
    faqQuestion3: 'What file formats are supported?',
    faqAnswer3: 'We support PDF, DOC, and DOCX formats. Our AI can extract content from both text-based and scanned PDFs.',
    faqQuestion4: 'How accurate is the matching?',
    faqAnswer4: 'Our AI achieves 95% match accuracy based on client feedback. We continuously improve our algorithms based on hiring outcomes.',
    faqQuestion5: 'Can I customize the matching criteria?',
    faqAnswer5: 'Yes! Recruiters can adjust weightage for different factors like skills, experience, education, and domain fit to match their specific hiring needs.',
    // Trust Badges
    trustedBy: 'Trusted by leading companies',
    security: 'Secure & Private',
    securityDesc: 'Enterprise-grade encryption',
    gdpr: 'GDPR Compliant',
    gdprDesc: 'Data protection guaranteed',
    support: '24/7 Support',
    supportDesc: 'Always here to help',
    // Footer
    footerTagline: 'AI-powered recruitment platform connecting exceptional talent with innovative companies.',
    quickLinks: 'Quick Links',
    resources: 'Resources',
    legal: 'Legal',
    contactUs: 'Contact Us',
    aboutUs: 'About Us',
    careers: 'Careers',
    blog: 'Blog',
    helpCenter: 'Help Center',
    documentation: 'Documentation',
    api: 'API',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    cookies: 'Cookie Policy',
    allRightsReserved: 'All rights reserved',
    // Testimonials
    testimonialsTitle: 'What Our Users Say',
    testimonialsSubtitle: 'Trusted by thousands of recruiters and candidates worldwide',
    testimonial1Name: 'Sarah Johnson',
    testimonial1Role: 'HR Director',
    testimonial1Company: 'TechCorp Inc.',
    testimonial1Quote: 'Hirevion revolutionized our recruitment process. We reduced hiring time by 60% and found candidates we would have never discovered through traditional methods.',
    testimonial2Name: 'Michael Chen',
    testimonial2Role: 'Senior Developer',
    testimonial2Company: 'StartupXYZ',
    testimonial2Quote: 'The CV analysis helped me understand my strengths and areas for improvement. I landed my dream job within weeks of using the platform.',
    testimonial3Name: 'Emily Williams',
    testimonial3Role: 'Recruitment Lead',
    testimonial3Company: 'GlobalTech Solutions',
    testimonial2Name: 'David Martinez',
    testimonial2Role: 'Software Engineer',
    testimonial2Company: 'InnovateTech',
    testimonial3Quote: 'The AI matching is incredibly accurate. It understood our requirements perfectly and presented candidates who were an excellent cultural fit.',
    // Stats
    statsTitle: 'Trusted by Industry Leaders',
    stats1Number: '50K+',
    stats1Label: 'CVs Analyzed',
    stats2Number: '95%',
    stats2Label: 'Match Accuracy',
    stats3Number: '10x',
    stats3Label: 'Faster Hiring',
    stats4Number: '500+',
    stats4Label: 'Companies',
    // Pricing
    pricingTitle: 'Simple, Transparent Pricing',
    pricingSubtitle: 'Choose the plan that fits your needs',
    pricingFree: 'Free',
    pricingFreeDesc: 'For individuals just starting out',
    pricingPro: 'Professional',
    pricingProDesc: 'For growing teams and recruiters',
    pricingEnterprise: 'Enterprise',
    pricingEnterpriseDesc: 'For large organizations',
    pricingPerMonth: '/month',
    pricingGetStarted: 'Get Started',
    pricingContactSales: 'Contact Sales',
    pricingFeature1: '5 CV analyses/month',
    pricingFeature2: 'Basic matching',
    pricingFeature3: 'Email support',
    pricingFeature4: 'Unlimited CV analyses',
    pricingFeature5: 'Advanced AI matching',
    pricingFeature6: 'Priority support',
    pricingFeature7: 'Custom integrations',
    pricingFeature8: 'Dedicated account manager',
    pricingFeature9: 'SLA guarantee',
    // Integrations
    integrationsTitle: 'Seamless Integrations',
    integrationsSubtitle: 'Connect with your favorite tools',
    // Blog
    blogTitle: 'Latest Insights',
    blogSubtitle: 'Tips and trends in AI-powered recruitment',
    blogReadMore: 'Read More',
    blogViewAll: 'View All Posts',
    // Landing Page
    landingTitle: 'Choose Your Path',
    landingTagline: 'Discover how Hirevion can transform your career or recruitment process.',
    recruiterTitle: "I'm a Recruiter",
    recruiterDesc: 'For companies, HR professionals and recruiters',
    talentTitle: "I'm a Talent",
    talentDesc: 'For job seekers and candidates',
    accessDashboard: 'Access Dashboard',
    accessPlatform: 'Access Platform',
    secureData: 'Secure Data',
    aiAccuracy: 'AI Accuracy',
  },
  fr: {
    getStarted: 'Commencer',
    analyzeMyCV: 'Analyser mon CV',
    forCandidates: 'Pour les candidats',
    forRecruiters: 'Pour les recruteurs',
    signIn: 'Se connecter',
    home: 'Accueil',
    dashboard: 'Tableau de bord',
    myCVs: 'Mes CVs',
    settings: 'Paramètres',
    signOut: 'Se déconnecter',
    chooseYourRole: 'Choisissez votre rôle',
    selectHowYouUseHirevion: 'Sélectionnez comment vous voulez utiliser Hirevion',
    imHiring: 'Je recrute et veux trouve des candidats',
    iWantToAnalyze: 'Je veux analyser et améliorer mon CV',
    // Landing pages
    chooseYourPath: 'Choisissez votre chemin',
    selectHowUseHirevion: 'Sélectionnez comment utiliser Hirevion',
    exploreHiring: 'Explorer le recrutement',
    jeSuisRecruteur: 'Je suis Recruteur',
    jeSuisTalent: 'Je suis Talent',
    findCandidates: 'Trouvez des candidats parfaits',
    findCandidatesDesc: 'Découvrez des talents exceptionnels grâce à notre système de matching IA avancé. Téléversez des CV, définissez vos exigences,得到的候选人的排名。',
    findCandidatesTitle: 'Trouvez les candidats parfaits avec l\'IA',
    improveCV: 'Analysez et améliorez votre CV',
    improveCVDesc: 'Téléchargez votre CV et recevez des commentaires instantanés. Découvrez vos forces, points faibles et suggestions personnalisées.',
    improveCVTitle: 'Analysez et améliorez votre CV avec l\'IA',
    getStartedFree: 'Commencer gratuitement',
    viewDemo: 'Voir la démo',
    scheduleDemo: 'Planifier une démo',
    whyRecruitersChoose: 'Pourquoi les recruteurs choisissent Hirevion?',
    powerfulAI: 'Outils IA puissants pour transformer votre recrutement',
    bulkProcessing: 'Traitement par lots',
    bulkProcessingDesc: 'Téléchargez des dizaines de CV à la fois. L\'IA classe instantanément tous les candidats avec des recommandations claires.',
    startFreeToday: 'Commencer gratuitement',
    join500Recruiters: 'Rejoignez 500+ recruteurs',
    readyToTransform: 'Prêt à transformer votre recrutement?',
    hiringDesc: 'Commencez à trouver des candidats exceptionnels aujourd\'hui. Aucune carte de crédit requise.',
    threeSimpleSteps: 'Trois étapes simples pour trouver vos candidats idéaux',
    whyTalentsLove: 'Pourquoi les talents adorent Hirevion?',
    improveChances: 'Recevez des commentaires professionnels et améliorez vos chances',
    instantAnalysis: 'Analyse instantanée',
    instantAnalysisDesc: 'Téléchargez votre CV et recevez des commentaires détaillés en quelques secondes. Connaissez votre score immédiatement.',
    improvementTips: 'Conseils d\'amélioration',
    improvementTipsDesc: 'Recevez des suggestions spécifiques pour améliorer votre CV. Conseils actionnables des experts IA.',
    atsOptimization: 'Optimisation ATS',
    atsOptimizationDesc: 'Assurez-vous que votre CV passe les systèmes de suivi des candidats. Soyez remarqué par les recruteurs.',
    threeSimpleStepsCV: 'Trois étapes simples pour améliorer votre CV',
    standOut: 'Prêt à vous démarquer?',
    standOutDesc: 'Analysez votre CV maintenant et soyez découvert par les meilleures entreprises.',
    join1000Talents: 'Rejoignez 1000+ talents',
    seeDemoResults: 'Voir les résultats de la démo',
    matchRate: 'Taux de correspondance',
    skillsDetected: 'Compétences détectées',
    cvsAnalyzed: 'CV analysés',
    goodMatch: 'Bon',
    strongMatch: 'Fort',
    needsWork: 'À améliorer',
    aiSuggestions: 'Suggestions IA',
    atsFriendly: 'Compatible ATS',
    ninetyFiveBetter: '95% meilleur',
    findPerfectProfile: 'Trouvez le Profil Parfait avec l\'IA',
    hirevionDescription: 'Hirevion met en relation des profils exceptionnels avec des entreprises innovantes. Notre IA analyse les compétences, l\'expérience et le potentiel pour trouver votre correspondance parfaite.',
    matchAccuracy: 'Précision des matchs',
    fasterHiring: 'Recrutement plus rapide',
    companiesTrustUs: 'Entreprises nous font confiance',
    whyChooseHirevion: 'Pourquoi choisir Hirevion?',
    revolutionaryAI: 'Technologie IA révolutionnaire pour le recrutement moderne',
    aiPoweredMatching: 'Matching alimenté par l\'IA',
    aiMatchingDesc: 'Des algorithmes avancés analysent les compétences, l\'expérience et le potentiel. La détection intelligente des compétences similaires reconnaît les technologies associées.',
    detailedAnalytics: 'Analyses détaillées',
    analyticsDesc: 'Obtenez des ventilations de score complètes: compétences (40%), expérience (25%), éducation (15%), adéquation au domaine (20%).',
    flexibleSelection: 'Sélection flexible',
    selectionDesc: 'Système à 4 niveaux: Excellent (80-100%), Bon (65-79%), Potentiel (50-64%). Trouvez des candidats avec du potentiel, pas seulement des correspondances parfaites.',
    howItWorks: 'Comment Hirevion fonctionne',
    simpleProcess: 'Processus simple en 3 étapes pour trouver vos candidats idéaux',
    uploadCVs: 'Téléverser des CV',
    uploadCVsDesc: 'Téléversez plusieurs CV PDF. Notre IA extrait des données structurées incluant les compétences, l\'expérience, l\'éducation et les projets.',
    defineJob: 'Définir le poste',
    defineJobDesc: 'Entrez le titre du poste, le nombre de postes et les exigences. L\'IA structure le profil et identifie les compétences clés requises.',
    getResults: 'Obtenir les résultats',
    getResultsDesc: 'Recevez les candidats classés avec un scoring détaillé, l\'analyse des forces/faiblesses et les recommandations d\'embauche.',
    readyToTransform: 'Prêt à transformer votre recrutement?',
    joinCompanies: 'Rejoignez des centaines d\'entreprises qui ont rationalisé leur processus de recrutement avec la plateforme alimentée par l\'IA de Hirevion.',
    startFreeToday: 'Commencer gratuitement',
    uploadYourCV: 'Téléverser votre CV',
    join500Companies: 'Rejoignez 500+ entreprises',
    login: 'Connexion',
    register: 'S\'inscrire',
    email: 'Email',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    fullName: 'Nom complet',
    forgotPassword: 'Mot de passe oublié?',
    noAccount: 'Vous n\'avez pas de compte?',
    haveAccount: 'Vous avez déjà un compte?',
    createAccount: 'Créer un compte',
    forgotPasswordTitle: 'Mot de passe oublié',
    forgotPasswordDesc: 'Entrez votre email et nous vous.enverrons un lien de réinitialisation',
    resetPassword: 'Réinitialiser le mot de passe',
    backToLogin: 'Retour à la connexion',
    // FAQ Section
    faqTitle: 'Questions Fréquemment Posées',
    faqSubtitle: 'Tout ce que vous devez savoir sur Hirevion',
    faqQuestion1: 'Comment fonctionne le matching IA de Hirevion?',
    faqAnswer1: 'Notre IA analyse les CV et les exigences des postes en utilisant le traitement naturel du langage avancé. Elle extrait les compétences, l\'expérience, l\'éducation et plus pour calculer les scores de compatibilité.',
    faqQuestion2: 'Mes données sont-elles sécurisées?',
    faqAnswer2: 'Absolument. Nous utilisons un chiffrement de niveau entreprise et ne partageons jamais vos données. Vos CV et informations restent complètement confidentiels.',
    faqQuestion3: 'Quels formats de fichiers sont supportés?',
    faqAnswer3: 'Nous supportons les formats PDF, DOC et DOCX. Notre IA peut extraire le contenu des PDF texte et scannés.',
    faqQuestion4: 'Quelle est la précision du matching?',
    faqAnswer4: 'Notre IA atteint 95% de précision basé sur les retours clients. Nous améliorons continuellement nos algorithmes.',
    faqQuestion5: 'Puis-je personnaliser les critères de matching?',
    faqAnswer5: 'Oui! Les recruteurs peuvent ajuster les pondérations pour les compétences, l\'expérience, l\'éducation et l\'adéquation au poste.',
    // Trust Badges
    trustedBy: 'Approuvé par les entreprises leaders',
    security: 'Sécurisé & Privé',
    securityDesc: 'Chiffrement de niveau entreprise',
    gdpr: 'Conforme RGPD',
    gdprDesc: 'Protection des données garantie',
    support: 'Support 24/7',
    supportDesc: 'Toujours disponible',
    // Footer
    footerTagline: 'Plateforme de recrutement alimentée par l\'IA connectant des talents exceptionnels avec des entreprises innovantes.',
    quickLinks: 'Liens Rapides',
    resources: 'Ressources',
    legal: 'Mentions Légales',
    contactUs: 'Contactez-nous',
    aboutUs: 'À propos',
    careers: 'Carrières',
    blog: 'Blog',
    helpCenter: 'Centre d\'aide',
    documentation: 'Documentation',
    api: 'API',
    privacy: 'Politique de confidentialité',
    terms: 'Conditions d\'utilisation',
    cookies: 'Politique des cookies',
    allRightsReserved: 'Tous droits réservés',
    // Testimonials
    testimonialsTitle: 'Ce que disent nos utilisateurs',
    testimonialsSubtitle: 'Approuvé par des milliers de recruteurs et candidats à travers le monde',
    testimonial1Name: 'Sarah Johnson',
    testimonial1Role: 'Directrice RH',
    testimonial1Company: 'TechCorp Inc.',
    testimonial1Quote: 'Hirevion a révolutionné notre processus de recrutement. Nous avons réduit le temps de recrutement de 60% et avons trouvé des candidats que nous n\'aurions jamais découverts par les méthodes traditionnelles.',
    testimonial2Name: 'Michael Chen',
    testimonial2Role: 'Développeur Senior',
    testimonial2Company: 'StartupXYZ',
    testimonial2Quote: 'L\'analyse du CV m\'a aidé à comprendre mes forces et les domaines à améliorer. J\'ai obtenu mon emploi idéal en quelques semaines grâce à la plateforme.',
    testimonial3Name: 'Emily Williams',
    testimonial3Role: 'Responsable Recrutement',
    testimonial3Company: 'GlobalTech Solutions',
    testimonial3Quote: 'Le matching IA est extrêmement précis. Il a parfaitement compris nos exigences et a présenté des candidats qui étaient un excellent ajustement culturel.',
    // Stats
    statsTitle: 'Approuvé par les leaders du marché',
    stats1Number: '50K+',
    stats1Label: 'CVs analysés',
    stats2Number: '95%',
    stats2Label: 'Précision du matching',
    stats3Number: '10x',
    stats3Label: 'Recrutement plus rapide',
    stats4Number: '500+',
    stats4Label: 'Entreprises',
    // Pricing
    pricingTitle: 'Tarification simple et transparente',
    pricingSubtitle: 'Choisissez le plan qui correspond à vos besoins',
    pricingFree: 'Gratuit',
    pricingFreeDesc: 'Pour les particuliers qui débutent',
    pricingPro: 'Professionnel',
    pricingProDesc: 'Pour les équipes en croissance',
    pricingEnterprise: 'Entreprise',
    pricingEnterpriseDesc: 'Pour les grandes organisations',
    pricingPerMonth: '/mois',
    pricingGetStarted: 'Commencer',
    pricingContactSales: 'Contacter les ventes',
    pricingFeature1: '5 analyses de CV/mois',
    pricingFeature2: 'Matching basique',
    pricingFeature3: 'Support par email',
    pricingFeature4: 'Analyses de CV illimitées',
    pricingFeature5: 'Matching IA avancé',
    pricingFeature6: 'Support prioritaire',
    pricingFeature7: 'Intégrations personnalisées',
    pricingFeature8: 'Gestionnaire de compte dédié',
    pricingFeature9: 'Garantie SLA',
    // Integrations
    integrationsTitle: 'Intégrations transparentes',
    integrationsSubtitle: 'Connectez-vous avec vos outils préférés',
    // Blog
    blogTitle: 'Dernières actualités',
    blogSubtitle: 'Conseils et tendances en recrutement IA',
    blogReadMore: 'Lire la suite',
    blogViewAll: 'Voir tous les articles',
    // Landing Page
    landingTitle: 'Choisissez votre parcours',
    landingTagline: 'Découvrez comment Hirevion peut transformer votre carrière ou votre processus de recrutement.',
    recruiterTitle: 'Je suis Recruteur',
    recruiterDesc: 'Pour les entreprises, RH et professionnels du recrutement',
    talentTitle: 'Je suis Talent',
    talentDesc: 'Pour les candidats et chercheurs d\'emploi',
    accessDashboard: 'Accéder au dashboard',
    accessPlatform: 'Accéder à ma plateforme',
    secureData: 'Données sécurisées',
    aiAccuracy: 'précision IA',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'fr' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
